### ISSUE TITLE
Russian

### ISSUE THREAD

**Issue by tsarkov90** [flyingdevelopmentstudio/infiniteflight-localization#18]
**What language do you wish to contribute?**
> **Russian**

**Comment by tsarkov90** [comment]
By the way, in the Russian language there are some peculiarities of the spelling of words related to time.

For example, we use different forms of the noun «час» and «день»  (means "hour" and "daty") in the next cases:

1 день - 1 day
2, 3, 4 дня - 2, 3, 4 days
5 дней - 5 days (and more)

1 час - 1 hour
2, 3, 4 часа - 2, 3, 4 hours
5 часов - 5 hours (and more)

What are the suggestions on what to do in that case?

1 hour, 2 hours, 3 hours, 4 hours, 5 hours

**Comment by carmichaelalonso** [comment]
Hi @tsarkov90! Thank you for offering to contribute. Russian has already been started by @squeezelemon - See issue https://github.com/flyingdevelopmentstudio/infiniteflight-localization/issues/9 and comment there in case there is an opportunity to help out :)

For the dates and times, we are looking into this on our end. Alexander has already mentioned this to me and I am investigating a way of doing this within the app directly to avoid the extra work for you.

благодарю вас!
