### ISSUE TITLE
French - Tips 

### ISSUE THREAD

**Issue by Baba-IF** [flyingdevelopmentstudio/infiniteflight-localization#22]
<div align = center> 

## Italian Language in Infinite Flight 

Hi Infinite Flight, I want to help you and adding the **Italian language** which is not my home language or a language that I know at the top but will learn about it and by learning, helping Infinite Flight have this language in the game. 

</div>

**Comment by Baba-IF** [comment]
Hi there, 

I prefer to help with a things that's in my home language, could I do the **Tips** that are missing for the french version please. 

Thanks in advance

**Comment by carmichaelalonso** [comment]
Hey @Baba-IF, thanks for offering to contribute!

We have an issue open for outstanding French corrections, I'll tag you there and we can continue the discussion :)
https://github.com/flyingdevelopmentstudio/infiniteflight-localization/issues/8

Regarding Italian, feel free to open a new issue for this, but it would be best to find somebody to peer-review it who is a native Italian speaker. Grazie!
